@startuml [自動化スクリプト]
  start
    :作業用フォルダ作成]
    :フォルダにWin10更新アシスタントダウンロード]
    :更新アシスタントをファイル指定]
    :画面表示無しでファイル実行] 
      note right: 今すぐアップデート開始
    :確認ダイアログをスキップ]
    :自動アップデート実行]
      if (実行中？) then (Yes)
      :アップデート中のダイアログは消さない]
      detach
      elseif (終了？) then(はい)
      :アップデート完了]
      else(いいえ)
      :アップデート失敗]
      detach
      endif 
    :win10更新アシスタントアンインストール]
  stop


    
@enduml
